// CUSTOMERS_LIST
export const GET_CUSTOMERS = "CustomersList/GET_CUSTOMERS";
export const GET_CUSTOMERS_SUCCESS = "CustomersList/GET_CUSTOMERS_SUCCESS";
export const GET_CUSTOMERS_FAILED = "CustomersList/GET_CUSTOMERS_FAILED";

// CUSTOMERS_DETAILS_VIEW
export const GET_CUSTOMER_DETAILS = "CustomerDetailView/GET_CUSTOMER_DETAILS";
export const GET_CUSTOMER_DETAILS_SUCCESS =
  "CustomerDetailView/GET_CUSTOMER_DETAILS_SUCCESS";
export const GET_CUSTOMER_DETAILS_FAILED =
  "CustomerDetailView/GET_CUSTOMER_DETAILS_FAILED";

// CUSTOMERS_DETAILS_FORM
export const UPDATE_CUSTOMER_DETAILS =
  "CustomerDetailForm/UPDATE_CUSTOMER_DETAILS";
export const UPDATE_CUSTOMER_DETAILS_SUCCESS =
  "CustomerDetailForm/UPDATE_CUSTOMER_DETAILS_SUCCESS";
export const UPDATE_CUSTOMER_DETAILS_FAILED =
  "CustomerDetailForm/UPDATE_CUSTOMER_DETAILS_FAILED";

export const CREATE_NEW_CUSTOMER =
  "CustomerDetailForm/CREATE_NEW_CUSTOMER";
export const CREATE_NEW_CUSTOMER_SUCCESS =
  "CustomerDetailForm/CREATE_NEW_CUSTOMER_SUCCESS";
export const CREATE_NEW_CUSTOMER_FAILED =
  "CustomerDetailForm/CREATE_NEW_CUSTOMER_FAILED";
